<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Crear</name>
   <tag></tag>
   <elementGuidId>fe2f74c8-11cf-40a1-b173-50d98fbdbaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12 > custom-button[type=&quot;primary&quot;] > p-button > button.p-ripple.p-button.p-component.primary > span.p-button-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-tabpanel[@id='pn_id_6_tabpanel_1']/app-admin-categoria/div[3]/div/p-card/div/div/div/div/div/custom-button/p-button/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Subtipo UsuarioCrear$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04ed3afa-bc08-46eb-931d-b38128d62325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label ng-star-inserted</value>
      <webElementGuid>0195dacd-2c5f-40a0-b93c-b4ec00c057fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>107f9d71-e150-41fc-bff5-74711211de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear</value>
      <webElementGuid>4652ece2-7a5e-4398-8438-cf502c0fd79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_6_tabpanel_1&quot;)/app-admin-categoria[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/p-card[1]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/custom-button[1]/p-button[1]/button[@class=&quot;p-ripple p-button p-component primary&quot;]/span[@class=&quot;p-button-label ng-star-inserted&quot;]</value>
      <webElementGuid>7415a9ac-9376-4196-beaa-5cac70cd4cd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabpanel[@id='pn_id_6_tabpanel_1']/app-admin-categoria/div[3]/div/p-card/div/div/div/div/div/custom-button/p-button/button/span</value>
      <webElementGuid>956814d8-dfec-4626-9a3f-61f8970f0abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtipo Usuario'])[1]/following::span[1]</value>
      <webElementGuid>1f32f46a-904e-4415-87d7-870082ad5df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrando 1 hasta 9 de 9 registros'])[1]/following::span[2]</value>
      <webElementGuid>95392951-6c77-409d-9816-04696597bacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/preceding::span[1]</value>
      <webElementGuid>303f8089-da5c-4eb7-898f-ba150fb0638c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[2]/preceding::span[1]</value>
      <webElementGuid>acc43ea0-c6b5-4a24-a260-1d845b64c084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/custom-button/p-button/button/span</value>
      <webElementGuid>ed6c350e-c6f3-495f-bcc3-9cc91e5e45aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Crear' or . = 'Crear')]</value>
      <webElementGuid>607dfb1b-2d46-4a7f-b15a-ae0cdbf96974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
