<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Documento de Prueba</name>
   <tag></tag>
   <elementGuidId>8c1fb96e-dce1-41b7-94a0-d78cd5c0b825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_11_0 > span.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_11_0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Documento de Prueba&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7881aa4e-bbee-4fd1-8b6b-83c925c23704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>c1aaa0b5-eb59-43ae-9ff8-7997920443fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documento de Prueba</value>
      <webElementGuid>129d9b30-36b5-4948-8c02-a23ad8bc4b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_11_0&quot;)/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>4e7eec05-7940-45ba-8ba2-3b47364bc7b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_11_0']/span</value>
      <webElementGuid>14da8202-40fd-48d3-8c91-17995cd6ba63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrando 1 hasta 1 de 1 registros'])[1]/following::span[3]</value>
      <webElementGuid>b56daa41-5f51-438a-957c-eb19be60784c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documento de Prueba']/parent::*</value>
      <webElementGuid>528a22f5-9564-40de-ada8-d6fdf2d9f308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>f53da912-b163-44ea-954b-06a32e88c93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Documento de Prueba' or . = 'Documento de Prueba')]</value>
      <webElementGuid>c5d1d255-8ad8-4176-99f5-7be167fd5075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
