<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fin_p-ripple p-button p-component p-_623048</name>
   <tag></tag>
   <elementGuidId>897b6d11-4694-4744-bd4f-d6d69897c686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-button.p-component.p-button-rounded.p-button-text.p-button-sm.p-datepicker-prev-button.p-button-icon-only</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Previous Month&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf94c7e4-7cd5-4b17-b997-6a3b6cc0e44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-button p-component p-button-rounded p-button-text p-button-sm p-datepicker-prev-button p-button-icon-only</value>
      <webElementGuid>b1fb3089-ff86-49c9-a912-361fea222d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c1d047dd-f40a-4e85-824f-5f12433d49ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07cdb735-13ee-42aa-a2d9-28e0dbd71abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous Month</value>
      <webElementGuid>65b2f10d-f45e-471c-af3d-87d6e6a892a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1034cafc-5e90-415b-8ac4-2f16c76891bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>bdfce0dc-0471-4c74-a2cc-801073574b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_8_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2825477640-3 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2825477640-3 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-header ng-tns-c2825477640-3&quot;]/p-button[@class=&quot;ng-tns-c2825477640-3&quot;]/button[@class=&quot;p-ripple p-button p-component p-button-rounded p-button-text p-button-sm p-datepicker-prev-button p-button-icon-only&quot;]</value>
      <webElementGuid>a26a2c7f-15c2-4cab-b383-5c72065f068e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>58b8219d-a1aa-4186-90b8-8deda7f63366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_8_panel']/div/div/div/p-button/button</value>
      <webElementGuid>0cf9f4bb-325f-4a9e-af51-56c2f481d6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio:'])[1]/following::button[1]</value>
      <webElementGuid>6c9a1586-875f-41d2-a98c-997ddcaca05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July'])[1]/preceding::button[1]</value>
      <webElementGuid>57166b31-0fbb-45c5-9a2e-7baf3ff6c499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::button[4]</value>
      <webElementGuid>76fc7b9c-55ca-444e-85fa-01ee5a5111ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-button/button</value>
      <webElementGuid>d24c6a15-4fbd-4797-b40d-00ea6d0e3cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>b9d47347-00e7-406f-9a90-3ce924cba8c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
