<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inicio_p-inputtext p-component ng-tns_0f9b9a</name>
   <tag></tag>
   <elementGuidId>ab1fa0b1-798d-4364-84c9-d6c8d554c048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.ng-tns-c2825477640-2.p-datepicker-input.p-filled.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Inicio:  July  2025 SuMoTuWeThFrSa29301234567891011121314151617181920212223242526272829303112&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b4a34be-aadb-4f88-b569-0e55c266cb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78d71854-0934-4567-b014-196b465d10a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>da82dea7-49ad-4372-b1b6-35cb5c2c4f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5927f42b-e427-4ed5-b2db-83f94c9ad502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>e3bb3c27-8b7b-41ea-9998-e058b2828113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>73f27870-7ebb-424d-b63d-b9d5524add33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component ng-tns-c2825477640-2 p-datepicker-input p-filled ng-star-inserted</value>
      <webElementGuid>de1aee48-9af3-4580-87fc-37ea8b50e1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>p-datepicker-input</value>
      <webElementGuid>fa93fd39-31c4-427c-8261-c66c31a7c31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Seleccione Fecha Inicio</value>
      <webElementGuid>b37ad267-5246-4007-ba86-c5c5cbc8e687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fluid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>196c7c95-b55b-4215-a64f-aa413f7509fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fd87ee4-f016-4940-8f10-e97f323ed034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_7_panel</value>
      <webElementGuid>1c561ad2-71c6-47cd-95de-76e68e23c72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_6_tabpanel_2&quot;)/app-admin-auditoria[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/p-card[1]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/label[3]/p-datepicker[@class=&quot;ng-tns-c2825477640-2 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c2825477640-2 p-datepicker p-component p-inputwrapper p-inputwrapper-focus p-focus&quot;]/input[@class=&quot;p-inputtext p-component ng-tns-c2825477640-2 p-datepicker-input p-filled ng-star-inserted&quot;]</value>
      <webElementGuid>8edc23f0-fed3-47f1-9917-1adb40102183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>1d5b0a43-2146-47b6-a683-a283068a9c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabpanel[@id='pn_id_6_tabpanel_2']/app-admin-auditoria/div/div/p-card/div/div/div/label[3]/p-datepicker/span/input</value>
      <webElementGuid>c9f00fe7-6b3c-48df-9e5f-484113040f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>299e8356-0bb6-4e61-87c4-650a67c5e780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Seleccione Fecha Inicio']</value>
      <webElementGuid>e2658d68-3d7c-4380-9885-dc2a8975ba9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
