<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_20</name>
   <tag></tag>
   <elementGuidId>44a04747-c68d-4b00-8daf-9c50b36dc7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_7_panel']/div/div/table/tbody/tr[3]/td[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;20&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21253555-ed8f-4347-b160-14d99b24aef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eea22e26-14d3-4ce7-a6e8-3973d98b5726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c2825477640-2 p-datepicker-day ng-star-inserted</value>
      <webElementGuid>46770748-985c-4957-b42a-ae3cd8b83d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a67d05e9-054a-486d-a1b3-8240f5037575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-5-20</value>
      <webElementGuid>a5c75b4c-f8f8-49e1-a87c-be8e34e0be05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>68e3dc2e-b5b5-4ef4-8631-4acf41669a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_7_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2825477640-2 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2825477640-2 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c2825477640-2 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c2825477640-2&quot;]/tr[@class=&quot;ng-tns-c2825477640-2 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c2825477640-2 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c2825477640-2 p-datepicker-day ng-star-inserted&quot;]</value>
      <webElementGuid>5150e651-8d49-4b34-a23c-6a39d6f336c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_7_panel']/div/div/table/tbody/tr[3]/td[6]/span</value>
      <webElementGuid>c08f686c-b5e9-4397-b5eb-6349a12ce405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[20]</value>
      <webElementGuid>5d290d21-c124-40cc-a423-470b5f53dab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[21]</value>
      <webElementGuid>2401d6c4-f352-410a-b678-0cd1a4377740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fin:'])[1]/preceding::span[16]</value>
      <webElementGuid>c265737a-ed58-472c-b838-e89bce85e0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::span[18]</value>
      <webElementGuid>e1ce8572-549a-42d5-80ef-6acfc3d147db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>f222da97-8891-4b4c-9db4-da106a23bcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/span</value>
      <webElementGuid>843ab3c8-b473-474f-a6f3-740044c34c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '20' or . = '20')]</value>
      <webElementGuid>cdcfeb74-c11d-4707-86e9-59b0fe290b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
