<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30</name>
   <tag></tag>
   <elementGuidId>82bf7187-5f88-46d7-a462-3a4790404193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pn_id_8_panel']/div/div/table/tbody/tr[5]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;30&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>202cd9f1-cf9f-40ab-ba31-7ce5575e3e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d2e3432-5369-4f35-85fe-7562ea02250c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple ng-tns-c2825477640-3 p-datepicker-day ng-star-inserted</value>
      <webElementGuid>99d40770-6ca9-477d-b9dc-f12082ed797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>4287eba6-827e-4fbb-ae25-97e40f41ca19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2025-5-30</value>
      <webElementGuid>203060b8-237a-400d-875f-0c3acf982561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3f4daf4a-5549-4b5b-a858-0ebadbd8592f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_8_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2825477640-3 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2825477640-3 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-day-view ng-tns-c2825477640-3 ng-star-inserted&quot;]/tbody[@class=&quot;ng-tns-c2825477640-3&quot;]/tr[@class=&quot;ng-tns-c2825477640-3 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c2825477640-3 p-datepicker-day-cell ng-star-inserted&quot;]/span[@class=&quot;p-ripple ng-tns-c2825477640-3 p-datepicker-day ng-star-inserted&quot;]</value>
      <webElementGuid>0894324c-be57-401d-90c4-bdc96f1fb1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pn_id_8_panel']/div/div/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>ba4d6e16-ca6c-4936-9574-df5eb594ce79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[30]</value>
      <webElementGuid>b2e1af49-712b-4090-a0b7-6b37d7c401c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[31]</value>
      <webElementGuid>8be6aad2-533d-4d41-9d72-948c40e42921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::span[6]</value>
      <webElementGuid>0fa4029e-fc49-4381-b0ee-73ce35f4fce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='txID'])[1]/preceding::span[7]</value>
      <webElementGuid>c6affcdb-5d0e-4d50-94e7-d70f72cef295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30']/parent::*</value>
      <webElementGuid>1b301c4a-7f7f-4299-b7f0-f564b979797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span</value>
      <webElementGuid>4ab39767-ce3a-4e9e-a73e-105f3b72bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '30' or . = '30')]</value>
      <webElementGuid>8f870efe-f269-4256-9e88-5e855ff70797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
