<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Subtipos de usuario cargados correctame_3e8323</name>
   <tag></tag>
   <elementGuidId>9ce41a5d-1cf6-4680-b43b-e3fa542bb245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>timesicon.p-component.p-iconwrapper.ng-tns-c2572556178-5.p-toast-close-icon.ng-star-inserted > svg.p-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtipos de usuario cargados correctamente'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.p-toast-close-button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8eab1198-7a21-4e7a-8fd4-c2cc0bd107ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>d0523072-a20e-4df8-b24e-7bc2b38428f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>b386c3aa-4ccd-41c0-8f3e-af7ee4c81e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 14 14</value>
      <webElementGuid>0d3dc8d0-b56c-4283-ab60-849f774cf991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7d096b21-407d-416c-bd74-c0b0ee214410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>64562215-ece9-4ede-9d1c-f67372a9fa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-icon</value>
      <webElementGuid>522ecef7-fb86-43ef-9c9e-0ddbdd2136e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48791350-153e-447a-9543-322116671720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/p-toast[@class=&quot;ng-tns-c757183554-0&quot;]/div[@class=&quot;p-toast p-component p-toast-top-right&quot;]/p-toastitem[@class=&quot;ng-tns-c2572556178-5 ng-trigger ng-trigger-toastAnimation ng-tns-c757183554-0 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2572556178-5 ng-trigger ng-trigger-messageState p-toast-message p-toast-message-info&quot;]/div[@class=&quot;ng-tns-c2572556178-5 p-toast-message-content ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2572556178-5 ng-star-inserted&quot;]/button[@class=&quot;p-toast-close-button&quot;]/timesicon[@class=&quot;p-component p-iconwrapper ng-tns-c2572556178-5 p-toast-close-icon ng-star-inserted&quot;]/svg[@class=&quot;p-icon&quot;]</value>
      <webElementGuid>e3a6240b-e29c-4eae-9bfe-1e0f7ce1aaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtipos de usuario cargados correctamente'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>05d1a19b-53ef-481a-b438-1c801b418b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtipos de Usuario'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>5cdf79a9-9e32-425e-95db-4e7ccd8f4359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos de Usuario'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>7f5f16ea-a762-4170-95b0-82bde77ac976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos de usuario cargados correctamente'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c5b1b34d-40cf-4099-8ffd-57bb7ff52cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
