<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Inicio_p-icon</name>
   <tag></tag>
   <elementGuidId>f6cbceb9-c973-440b-ae73-3fcdcaa057af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>chevronlefticon.p-component.p-iconwrapper.ng-tns-c2825477640-2.ng-star-inserted > svg.p-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitante:'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Previous Month&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f98121a5-45df-4ccd-b984-96b75587c6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>50d64537-936c-46a6-8096-845d9f4575b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>53ec5ec3-d5ab-4ca2-a7d6-cb2ec87b40df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 14 14</value>
      <webElementGuid>58c13fa0-50d0-48f6-8a25-b3de7849ea02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>87775d70-3413-4666-8d91-6a4a28e29704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>f6eb4266-6097-405a-8f17-75b744f59f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-icon</value>
      <webElementGuid>226eebeb-38ac-4221-a1b5-f3cd80a67514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>141f0d04-1b13-4ea0-a5db-747b6605c387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_7_panel&quot;)/div[@class=&quot;p-datepicker-calendar-container ng-tns-c2825477640-2 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar ng-tns-c2825477640-2 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-header ng-tns-c2825477640-2&quot;]/p-button[@class=&quot;ng-tns-c2825477640-2&quot;]/button[@class=&quot;p-ripple p-button p-component p-button-rounded p-button-text p-button-sm p-datepicker-prev-button p-button-icon-only&quot;]/chevronlefticon[@class=&quot;p-component p-iconwrapper ng-tns-c2825477640-2 ng-star-inserted&quot;]/svg[@class=&quot;p-icon&quot;]</value>
      <webElementGuid>39cf476d-4998-474b-b387-1fc1c67a95c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitante:'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>a19f67a6-a8ae-4099-8149-abd5d18687bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c9a44f70-47e2-473d-a760-1a10d33efc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c6ba0830-2a75-465c-aeb8-4a4b974e9b90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
