<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Crear</name>
   <tag></tag>
   <elementGuidId>3188033a-bcfc-4871-985f-ee5dc7f86223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-button-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-tabpanel[@id='pn_id_6_tabpanel_1']/app-admin-categoria/div/div/p-card/div/div/div/custom-button/p-button/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p-card >> internal:has-text=/^Tipo UsuarioRealize y registre aquí un nuevo tipo\.Crear$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4280857-276a-4c7f-b9da-a856a693565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label ng-star-inserted</value>
      <webElementGuid>2167080d-2848-4552-b627-f8fad1c28a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>26b38509-1773-438b-a09d-91994d4f7f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear</value>
      <webElementGuid>56a8fc95-f92e-4975-b8e4-3ff3c0520694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_6_tabpanel_1&quot;)/app-admin-categoria[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-12&quot;]/p-card[1]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/custom-button[1]/p-button[1]/button[@class=&quot;p-ripple p-button p-component primary&quot;]/span[@class=&quot;p-button-label ng-star-inserted&quot;]</value>
      <webElementGuid>274b50d3-73ff-40fc-82dd-5cba6c41fd12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabpanel[@id='pn_id_6_tabpanel_1']/app-admin-categoria/div/div/p-card/div/div/div/custom-button/p-button/button/span</value>
      <webElementGuid>28bfb66e-7954-40f5-9186-3c8c138d6929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Usuario'])[1]/following::span[1]</value>
      <webElementGuid>89039015-95fc-4bfa-94aa-2e63240bcd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auditoría'])[1]/following::span[2]</value>
      <webElementGuid>bf96c426-ddc7-48b3-b2b7-d70a41c647a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::span[1]</value>
      <webElementGuid>62f3db8b-8441-4c43-b804-d38c48e161b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/preceding::span[1]</value>
      <webElementGuid>c562f0ac-12e4-4c6b-b07f-12aab5c8222e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crear']/parent::*</value>
      <webElementGuid>3a10e8e2-6bb3-4a73-bb10-9b24d8e67647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>c5c6b21d-aa77-4a2d-b1b0-f9a495dcddfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Crear' or . = 'Crear')]</value>
      <webElementGuid>1ad35121-4db3-4323-858c-c5e35c2b953e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
