<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Institucion Publica</name>
   <tag></tag>
   <elementGuidId>8c4489ed-8b9a-46b6-a1e9-d8adaf586d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_12 > span.p-select-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='pn_id_12']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Institucion Publica&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2f1355e-11f6-4fc1-abc4-47285bcdf836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>1290d8f1-a199-46d7-9d38-54ff0ffc3155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>89fdfa99-01a8-4937-ad39-c22953891389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tooltip-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>89af911a-efdb-4c2b-b2ef-8495f74b89aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position-style</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>89d134de-9ebe-4205-835e-2e63ea1fde7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69139228-a7ae-452f-9c22-b14afdc936c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Institucion Publica</value>
      <webElementGuid>61327ab3-b4a5-4ea1-bd7e-3d48eb8d10a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>0c7dd28e-0faf-4c3c-919a-2ca45f80dce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce35ff87-00ee-4eaa-8515-1226afff6ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e45d1996-0431-4144-a8a2-2e106a44bceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-label ng-star-inserted</value>
      <webElementGuid>77a03cfe-a277-4ff0-b47d-e258d65a16e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Institucion Publica</value>
      <webElementGuid>7eb1189a-843b-4230-8cdc-d704d9e2ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_12&quot;)/span[@class=&quot;p-select-label ng-star-inserted&quot;]</value>
      <webElementGuid>a709d8f1-545d-4510-8818-1623df4ff4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='pn_id_12']/span</value>
      <webElementGuid>095aa1b7-80bf-4a18-b37c-f9f3ded5e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubTipo'])[1]/following::span[1]</value>
      <webElementGuid>cb42bf58-594a-4a54-bd5c-6021568c8bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UsuarioTest'])[1]/following::span[1]</value>
      <webElementGuid>a6f74278-212a-441d-b6ef-3dd3630269d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activo'])[8]/preceding::span[1]</value>
      <webElementGuid>83b90258-d6a8-42be-bdad-7db9f3ae453c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicar Cambios'])[1]/preceding::span[1]</value>
      <webElementGuid>fb85e575-507f-4a09-a77a-dc9adfbcb0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Institucion Publica']/parent::*</value>
      <webElementGuid>e66778b9-ed1d-4c02-a128-1b0a22d24532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-select/p-dropdown/span</value>
      <webElementGuid>419e0390-2747-46d0-9eb5-6717cacf7644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Institucion Publica' or . = 'Institucion Publica')]</value>
      <webElementGuid>96f8eec7-92f8-4310-9d75-3fc0dfcc21ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
