<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Institucion_1 (1)</name>
   <tag></tag>
   <elementGuidId>c69c20a3-0adf-4a46-9eb5-5e4ea8e92aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_14_2 > span.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_14_2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Institucion&quot;i >> internal:text=&quot;Institucion&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e526eec5-3c76-4c1f-bb96-37543c9251cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>107462ca-a4bf-480a-8a37-3c6078779aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Institucion</value>
      <webElementGuid>02b01f96-b82a-47af-85d4-0192a1a57332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_14_2&quot;)/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>37eea847-a015-4e0f-881d-4d62b753e3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_14_2']/span</value>
      <webElementGuid>2665bbd8-5ffc-4bd7-8c4d-7920e25b71ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[3]/following::span[1]</value>
      <webElementGuid>27a66515-c055-4af1-b0c8-8c0b67d7bd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::span[2]</value>
      <webElementGuid>12adc37a-5d19-46ea-8086-4161b631ef8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UsuarioTest'])[3]/preceding::span[1]</value>
      <webElementGuid>451f95f4-8cd5-4e90-9b8d-ec11a5801ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TipoUsuario_'])[1]/preceding::span[2]</value>
      <webElementGuid>a186d4d2-cec3-43a0-9bb5-ac67e611f04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[3]/li/span</value>
      <webElementGuid>149d3bc8-1cdd-4274-9dce-590d92abe579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Institucion' or . = 'Institucion')]</value>
      <webElementGuid>59f03153-e942-4865-8411-064a6d3a250b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
