<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TiposUsuarioPrueba_1</name>
   <tag></tag>
   <elementGuidId>7e871c1c-21f0-41ad-945a-a2344f5ab8c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_16 > span.p-select-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='pn_id_16']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;TiposUsuarioPrueba&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d9c1641-99b6-469d-a240-f97407a32fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>dd57fd85-85db-4863-82f1-4457ae11d55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5673399a-dfdf-4c72-9610-726f18d26980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tooltip-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>48f6a132-7ecf-45c9-b2a8-e1a2c3df3e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position-style</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>514bb038-c66a-4ab6-8577-a21085bfeefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc1c8742-099a-4bdf-9f2b-b129e5f96f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TiposUsuarioPrueba</value>
      <webElementGuid>85dd1936-4d26-44f0-ba0f-e223fbcee539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>06b4cd7d-e1b3-44b4-9778-63b2954445e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2b80677-6b26-4dee-a3c6-85afa9e99416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>303aa173-3a02-4550-9e28-d0794135b7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-label ng-star-inserted</value>
      <webElementGuid>819f4763-e2df-4bf0-b30c-a06c93e5137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TiposUsuarioPrueba</value>
      <webElementGuid>fc37ff1e-c889-405d-b29f-a651cff24cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_16&quot;)/span[@class=&quot;p-select-label ng-star-inserted&quot;]</value>
      <webElementGuid>984c164d-3ba6-4864-8107-feab6c4f2ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='pn_id_16']/span</value>
      <webElementGuid>c34d06eb-31f2-431f-8658-078ca87aa4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubTipo'])[1]/following::span[1]</value>
      <webElementGuid>aa2ef1d9-0f06-4fc6-bbcb-e2bc203aa38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institucion'])[2]/following::span[1]</value>
      <webElementGuid>d3ef8c3e-157c-4751-a8e9-f7503bf33653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activo'])[7]/preceding::span[1]</value>
      <webElementGuid>f4d4710f-1005-42c3-a4cd-cf8f6cac2fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicar Cambios'])[1]/preceding::span[1]</value>
      <webElementGuid>98325b1f-f89e-485e-abef-6c4ca5c6618c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TiposUsuarioPrueba']/parent::*</value>
      <webElementGuid>c39bdad5-a46d-4c07-a843-acc1e73369dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-select/p-dropdown/span</value>
      <webElementGuid>60c97cdd-4e16-4d4f-8aa8-4655cfbd20b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TiposUsuarioPrueba' or . = 'TiposUsuarioPrueba')]</value>
      <webElementGuid>1ab18823-f272-4612-a9b0-db37938ce209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
