<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TiposUsuarioPrueba</name>
   <tag></tag>
   <elementGuidId>dfd4451c-616c-487e-a89c-3c09b8fb6802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_12_4 > span.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pn_id_12_4']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;TiposUsuarioPrueba&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0f74133-0af5-4275-af56-b70190220ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>fa0a5567-f445-46b7-b90f-d8038992c092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TiposUsuarioPrueba</value>
      <webElementGuid>22c31556-78b5-473e-b8b2-a0410aaaca09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_12_4&quot;)/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>2a49d594-489b-42bc-b5ac-e0547b388da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pn_id_12_4']/span</value>
      <webElementGuid>2fc2afb9-6d79-4806-a0f7-a0cadbe4b786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institucion Privada'])[1]/following::span[1]</value>
      <webElementGuid>4666736a-c405-41da-8a2a-3890b08127b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institucion Publica'])[2]/following::span[2]</value>
      <webElementGuid>9ff295b0-4e31-4388-865f-de2d7cbcb1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubTipo_'])[1]/preceding::span[1]</value>
      <webElementGuid>be01f5d1-5fac-4a18-a4a4-20d1b0cbf53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubTipo_'])[2]/preceding::span[2]</value>
      <webElementGuid>4c539c49-62ad-4a5a-8d27-db63b9c19f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TiposUsuarioPrueba']/parent::*</value>
      <webElementGuid>7500d8c1-c037-4bb7-840f-bd30d38b8eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[5]/li/span</value>
      <webElementGuid>8fe26e37-759d-415f-bf83-2aad0069abb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TiposUsuarioPrueba' or . = 'TiposUsuarioPrueba')]</value>
      <webElementGuid>4ee29e65-8809-496b-a2d4-a4c5fa70d939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
