<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UsuarioTest (1)</name>
   <tag></tag>
   <elementGuidId>8ffd411b-a051-47b2-8dcb-975acde3b9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-select-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='pn_id_14']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;UsuarioTest&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e5ea288-62ac-41a3-bb72-524e16ea10c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>16d470d8-9fad-4553-9bd2-e994e7f1e88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c2f76017-35f8-48b9-a811-b7310c926e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tooltip-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>d6948fd3-4444-4eff-baab-e94ed03911f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position-style</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>10244906-7b3c-4cd8-8e6b-b38627de8397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>282bad5e-e29b-4c78-b4d0-ff3862614bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>UsuarioTest</value>
      <webElementGuid>7c8366d9-3822-4afe-a56f-bc092ce1059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>8225fc07-a069-47f5-be2d-28a6d0bbbb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aae73d46-abdb-4045-86e5-635fb8dbf7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd48fd18-3f6f-46e3-97bd-dd144a593d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-label ng-star-inserted</value>
      <webElementGuid>0bc29bc9-00e5-4e77-87e2-fb503ae1f872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsuarioTest</value>
      <webElementGuid>896a2fec-afbe-4db8-a282-ed6af45edea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_14&quot;)/span[@class=&quot;p-select-label ng-star-inserted&quot;]</value>
      <webElementGuid>4b684f05-3fc5-45c0-a8ca-2ce06b08b5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='pn_id_14']/span</value>
      <webElementGuid>c40f5b26-bc2c-4d59-9f8f-2686612cb841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[2]/following::span[1]</value>
      <webElementGuid>efef5645-1b08-489c-94f4-ca808e27eb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[2]/following::span[1]</value>
      <webElementGuid>e9c3a234-a384-42fa-9384-65c8ad9e8399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubTipo'])[1]/preceding::span[1]</value>
      <webElementGuid>e16d750f-5a9a-4c79-8577-cb35737d24ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TiposUsuarioPrueba'])[1]/preceding::span[1]</value>
      <webElementGuid>855655f0-260f-4945-adfc-7f7bca49aabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdown/span</value>
      <webElementGuid>da3f3752-cda8-4687-b4ed-0148aaef9ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'UsuarioTest' or . = 'UsuarioTest')]</value>
      <webElementGuid>e8580fba-ed81-4ece-86b3-d3cc6f8ba3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
