<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-dropdown_-- selecciona --</name>
   <tag></tag>
   <elementGuidId>a728fbc0-f6ce-4bac-909c-911b284a093a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='pn_id_14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pn_id_14</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-dropdown</value>
      <webElementGuid>ef9e06e5-6f97-4a60-9dd7-6a09f47b7283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>appendto</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>b49ea4aa-5f44-495a-87bd-9ce5ef0ca456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-append-to</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>af0ef7cb-684a-4370-b884-28e80da41ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>36c1ac80-2098-4abd-8591-eff001e398e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-option-label</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>bcca7a0b-f4d0-43e3-9b0d-62df78ceb197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-option-value</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>3308902a-294e-45f8-aa48-c48df20e8de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>-- selecciona --</value>
      <webElementGuid>2b2fd05f-a45c-4e11-a288-a3fc1a4d8712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30a54e00-826b-46bd-b3c4-f22b7fa1ac03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43c45b60-6b87-4d1d-b7a9-13181a7593a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_14</value>
      <webElementGuid>8ba1532f-0906-43b0-8a30-9feb7487715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-component p-dropdown p-inputwrapper p-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9c51f6e8-d875-488a-a927-e2f98ac06c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- selecciona --</value>
      <webElementGuid>cb08b3b6-d550-4211-ae9d-33d0ee52879d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_14&quot;)</value>
      <webElementGuid>41adaf69-cc45-4b16-ae0f-2ae33b0fc43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-dropdown[@id='pn_id_14']</value>
      <webElementGuid>bb8eee5d-f090-42f5-8b63-014739eec9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabpanel[@id='pn_id_6_tabpanel_2']/app-instituciones-otras-solicitudes/div/div/p-card/div/div/div/form/label[2]/app-select/p-dropdown</value>
      <webElementGuid>b63af6c4-1dff-4e7a-8e14-9288d2be8e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='institucion2'])[1]/following::p-dropdown[1]</value>
      <webElementGuid>c1f2d200-9965-4486-b683-61d2d98fb996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitar'])[2]/preceding::p-dropdown[1]</value>
      <webElementGuid>980c5a66-24ed-46ca-a2dc-56363933f5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/app-select/p-dropdown</value>
      <webElementGuid>b2fbd530-2930-4696-a514-e79c0c0af52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-dropdown[@id = 'pn_id_14' and (text() = '-- selecciona --' or . = '-- selecciona --')]</value>
      <webElementGuid>bcc72cba-ff48-4cff-97c3-3ffb31474555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
