<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-tab_Realizar Solicitudes</name>
   <tag></tag>
   <elementGuidId>95656e2b-6c49-4572-af1e-fd8afd6119ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_6_tab_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-tab[@id='pn_id_6_tab_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Realizar Solicitudes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-tab</value>
      <webElementGuid>bbc4ebbe-fc78-42ab-8182-5c2b0e800330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-tab p-component ng-star-inserted</value>
      <webElementGuid>326fa151-edc8-4a09-9494-a5dbb2f0dcff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2148a1af-8546-4493-8bf9-ce230b154b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c419ac9a-5f1c-4207-a5d3-c7a407158f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_6_tab_2</value>
      <webElementGuid>c04ce9f6-3ed6-4ee0-bccb-9f157c782c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_6_tabpanel_2</value>
      <webElementGuid>e7b30cc3-90d8-4dd3-aaa7-bdb32c80c7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c16e7374-e37f-4024-b0d2-574022fd990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2b7ef1c-2c21-4809-86b9-594a032b8a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2946cea-8277-4738-b764-38f2f79e1a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1103bd2c-57bb-495d-9fe5-255064c76b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>679a4e77-c0bc-45b0-9268-ed9dd148e9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Realizar Solicitudes</value>
      <webElementGuid>20a23d46-3b99-460c-ad58-d7962499f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_6_tab_2&quot;)</value>
      <webElementGuid>1e17feeb-aea9-443a-b682-831b0cafdef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-tab[@id='pn_id_6_tab_2']</value>
      <webElementGuid>19622947-da46-4e37-9bc0-03ecaca17d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabs[@id='pn_id_6']/p-tablist/div/div/p-tab[3]</value>
      <webElementGuid>87140c91-a4bc-4143-95e6-2b613e5c9537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrar Tipos Documentos'])[1]/following::p-tab[1]</value>
      <webElementGuid>70fc1d37-e6dc-4aca-b5d0-3372d5a4f4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emitir Documentos'])[1]/following::p-tab[2]</value>
      <webElementGuid>0973d5d8-2e48-4721-9f95-998330d70b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emitir'])[1]/preceding::p-tab[1]</value>
      <webElementGuid>6e9f6773-1872-4f2d-9b55-26ecb163ccbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::p-tab[1]</value>
      <webElementGuid>33996ff0-fc22-4b86-a8e0-5c0ff6f38a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Realizar Solicitudes']/parent::*</value>
      <webElementGuid>5c785c9e-8514-4353-a184-f685ce6321f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tab[3]</value>
      <webElementGuid>24aa2796-24f1-4442-95b5-d611e8da24a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-tab[@id = 'pn_id_6_tab_2' and (text() = 'Realizar Solicitudes' or . = 'Realizar Solicitudes')]</value>
      <webElementGuid>a64e1510-c3f3-4917-a13c-93c487bfdfa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
