<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-tab_Administrar Tipos Documentos</name>
   <tag></tag>
   <elementGuidId>feb6ed7d-d6dd-4677-bb3b-4ef5dd13bdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pn_id_6_tab_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-tab[@id='pn_id_6_tab_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Administrar Tipos Documentos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-tab</value>
      <webElementGuid>c3da85b8-b0ef-4e5d-bc3e-82532fb03701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-tab p-component ng-star-inserted</value>
      <webElementGuid>bd4e8421-cbb8-4196-a1ef-9a66b5fdd051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1dc873f3-0e92-47e4-a97d-80695afdb8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c93ac172-5e5f-4b86-a457-4ee8fd636bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pn_id_6_tab_1</value>
      <webElementGuid>6878c587-fb4c-4ff3-b157-ebcd5e15566b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pn_id_6_tabpanel_1</value>
      <webElementGuid>33246bbb-d3c1-478c-988a-2f892da4def0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7d639ed4-de13-4fb4-91e0-bb1c6376f9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e1b5fb3-325e-4961-80e3-7316922ac3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4ed5fa6-fc9c-4d82-93d6-4dacd10d203e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91f20d8f-81e7-42eb-a8f5-b833834ec41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0133bdc6-0478-4bae-8e49-4c355218d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrar Tipos Documentos</value>
      <webElementGuid>d7eb2cad-752c-4f85-aba3-3b102750318e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pn_id_6_tab_1&quot;)</value>
      <webElementGuid>a79660e1-a36a-48b8-9a03-2f560c70730a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-tab[@id='pn_id_6_tab_1']</value>
      <webElementGuid>b8102ded-d9d4-4716-ac5c-613a90c3372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-tabs[@id='pn_id_6']/p-tablist/div/div/p-tab[2]</value>
      <webElementGuid>11eaa248-c4bf-4095-849b-95e9050858a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emitir Documentos'])[1]/following::p-tab[1]</value>
      <webElementGuid>4889d819-eb13-4465-b3ae-79a71300487e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Cuenta'])[1]/following::p-tab[2]</value>
      <webElementGuid>bbaeb81e-fa6f-4a76-8a89-df0b2c727e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Realizar Solicitudes'])[1]/preceding::p-tab[1]</value>
      <webElementGuid>7bbb0d66-81b7-4e44-8456-b3b7ad692d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emitir'])[1]/preceding::p-tab[2]</value>
      <webElementGuid>4899cb09-914f-4ac7-99a8-e83bc1630714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrar Tipos Documentos']/parent::*</value>
      <webElementGuid>b53e0cc6-12b6-4b0e-ab53-a6f641ff5801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tab[2]</value>
      <webElementGuid>8dd16002-0b58-463c-8b2d-8f83f0d18000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-tab[@id = 'pn_id_6_tab_1' and (text() = 'Administrar Tipos Documentos' or . = 'Administrar Tipos Documentos')]</value>
      <webElementGuid>fa69c238-27bc-4b86-95b5-4faf87cc5f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
